### ISSUE TITLE
get mega_xvec_dict

### ISSUE THREAD

**Issue by miaott1234** [iiscleap/NeuralPlda#1]
hi, i want to know how to get mega_xvec_dict files

**Comment by iiscleap** [comment]
The last stage in dataprep_sre.py or dataprep_voices.py generates the mega_xvec_dict pickle file. You'll need to modify your paths accordingly. It is basically a python dictionary of xvectors of the format {uttid: xvector npy array}, consisting of all the train, test and evaluation xvectors for a particular experiment. We use kaldi-io to load the xvectors from kaldi ark/scp files.

**Comment by miaott1234** [comment]
so i should get xvector embeddings using kaldi tools firstly, is that right?

**Comment by iiscleap** [comment]
We have extracted the x-vector embeddings from a kaldi model. But you could get it from any model like tensorflow or pytorch implementations and use the NPLDA code. If you would like to reproduce our results in the paper, you can extract the xvectors with kaldi using the MFCC configuration provided in the `conf/` folder, and the `final.raw` model in `kaldi_models` folder.
