### ISSUE TITLE
questions about nplda

### ISSUE THREAD

**Issue by forwiat** [iiscleap/NeuralPlda#5]
hello iiscleap,
Thank you so much for the great work you've shared.
I have a question about the model loss. firstly, can I simplify the model loss to 'function(sigmoid(scores), target)'? (I don't konw if i understand it ...). Then, the scores can be regarded as loglikelihood radio? If can, how to explain it?

Thanks you!

**Comment by iiscleap** [comment]
Hi,
Thank you for showing interest in our work. The loss function that we use is a soft version of the detection cost function (DCF), which we denote as softCdet.  The threshold at which this loss is computed is one of the model parameters. Hence it is arbitrary. In this case, when you write this function in the form '`function(sigmoid(scores), target)`', then the scores can not be treated as a log-likelihood ratio. The scores can be treated as log-likelihood ratios only for certain functions which penalize for bad calibration as discussed in the paper http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.217.7404&rep=rep1&type=pdf.
An example of such a loss function is the Cllr.
Regards.

**Comment by forwiat** [comment]
Oh! Thanks a lot! this paper may be very useful for me. ( BTW, the problem that bothers me may be solved, haha:)
