### ISSUE TITLE
mega_xvector_voices_voxceleb_16k.pkl

### ISSUE THREAD

**Issue by 919275335** [iiscleap/NeuralPlda#7]
How can i get this file?

**Comment by iiscleap** [comment]
To generate mega_xvector* pickle files, you need to extract the x-vectors or any other embeddings of your datasets using Kaldi or any other implementation. Once you have the x-vector ark or scp files generated in Kaldi, all you have to do is edit the paths in the script https://github.com/iiscleap/NeuralPlda/blob/master/dataprep_voices_challenge.py and run this script. It will generate the file mega_xvector_voices_voxceleb_16k.pkl
